import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full flex justify-center min-h-dvh bg-gray-200 text-foreground">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
